version: "3.8"

services:
  planning-poker:
    container_name: pp-be

    image: planning-poker-be
    build:
      context: ../..
      dockerfile: ./backend/Dockerfile
    networks:
      - planning-poker-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${HOST_ADDRESS}`) && PathPrefix(`/api`) || Host(`${HOST_ADDRESS}`) && PathPrefix(`/socket.io`)"
      - "traefik.http.services.backend.loadBalancer.server.port=8000"

      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.backend.middlewares=cors"

  traefik:
    container_name: pp-traefik

    image: traefik:v2.11
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
    networks:
      - planning-poker-net

  web:
    container_name: pp-web

    image: planning-poker-web
    build:
      context: ../..
      dockerfile: ./frontend/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${HOST_ADDRESS}`)"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
    networks:
      - planning-poker-net

networks:
  planning-poker-net:
    external: false
    name: planning-poker-net
